FROM mcr.microsoft.com/devcontainers/base:ubuntu
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends pkg-config cmake gcc g++ gdb libncurses-dev libicu-dev nettle-dev libgtest-dev \
    && rm -rf /var/lib/apt/lists/*
